### ISSUE TITLE
it broke for my stream :(

### ISSUE THREAD

**Issue by cgsdev0** [strager/First#22]
when I started streaming today, someone redeemed the 'first' reward, and it didn't update their score or the reward. After I re-logged in on the website, it did work. I suspect something to do with my token not being refreshed properly, but I couldn't figure out an obvious explanation from my read of the code.

Here's a link to the VOD when it happened https://www.twitch.tv/videos/1903634978?t=0h1m55s

**Comment by strager** [comment]
Yeah, it's broken for my stream too.

@mate-amargo Do we just need to restart the server?

**Comment by mate-amargo** [comment]
Looking at the logs 
```
INFO:first.twitch_eventsub:stopping thread...
INFO:first.twitch_eventsub:WebSocket closed with an error
Traceback (most recent call last):
  File "[redacted]/twitch_eventsub.py", line 258, in _handle_client
    message = client.recv()
              ^^^^^^^^^^^^^
  File "[redacted]/.tox/flask/lib/python3.11/site-packages/websockets/sync/connection.py", line 198, in recv
    raise self.protocol.close_exc from self.recv_events_exc
websockets.exceptions.ConnectionClosedError: sent 1000 (OK); no close frame received
```
we are getting an unhandled exception, the problem is that we're catching the wrong thing:
https://github.com/strager/First/blob/master/first/twitch_eventsub.py#L259
It should be `websockets.exceptions.whatever` I've fixed the `except` clause in this [branch](https://github.com/strager/First/compare/master...MoreToxicTox) together with a bunch of other changes to tox.

**Comment by strager** [comment]
@mate-amargo fixed some issues on the server and make scoring work.

However, Twitch's API changed: the First! app can only manage channel point rewards created by the First! app. If you made a custom reward manually then selected it in First! (like I did), you'll need to rename or delete it then recreate it using the First! app. I did this and it's working for me now.
